[package]
name = "aoc2022"
version = "0.2.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["Day02"]

[workspace.dependencies]
aoc2022 = { path = ".", version = "0.2.2" }

[dependencies]
